// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PJATK_APBD_Cw7_s33986.Infrastructure;

#nullable disable

namespace PJATK_APBD_Cw7_s33986.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516135933_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.Component", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("char(10)");

                    b.Property<int>("ComponentManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("ComponentTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Code");

                    b.HasIndex("ComponentManufacturerId");

                    b.HasIndex("ComponentTypeId");

                    b.ToTable("Components");

                    b.HasData(
                        new
                        {
                            Code = "CPU0000001",
                            ComponentManufacturerId = 1,
                            ComponentTypeId = 1,
                            Description = "8-core gaming processor",
                            Name = "Ryzen 7 7800X3D"
                        },
                        new
                        {
                            Code = "GPU0000001",
                            ComponentManufacturerId = 2,
                            ComponentTypeId = 2,
                            Description = "High-end gaming graphics card",
                            Name = "RTX 4080 Super"
                        },
                        new
                        {
                            Code = "RAM0000001",
                            ComponentManufacturerId = 3,
                            ComponentTypeId = 3,
                            Description = "DDR5 RAM module 16GB",
                            Name = "Corsair Vengeance DDR5 16GB"
                        },
                        new
                        {
                            Code = "SSD0000001",
                            ComponentManufacturerId = 4,
                            ComponentTypeId = 4,
                            Description = "NVMe SSD 1TB",
                            Name = "Samsung 990 PRO 1TB"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.ComponentManufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("FoundationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("ComponentManufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AMD",
                            FoundationDate = new DateTime(1969, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Advanced Micro Devices"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "NV",
                            FoundationDate = new DateTime(1993, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "NVIDIA Corporation"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "COR",
                            FoundationDate = new DateTime(1994, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Corsair Gaming Inc."
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SAM",
                            FoundationDate = new DateTime(1969, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FullName = "Samsung Electronics"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.ComponentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ComponentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "CPU",
                            Name = "Processor"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "GPU",
                            Name = "Graphics Card"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "RAM",
                            Name = "Memory"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "SSD",
                            Name = "Storage"
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.PC", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("Warranty")
                        .HasColumnType("int");

                    b.Property<double>("Weight")
                        .HasColumnType("float(5)");

                    b.HasKey("Id");

                    b.ToTable("PCs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 8, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gaming Beast X",
                            Stock = 5,
                            Warranty = 36,
                            Weight = 12.5
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 15, 13, 30, 0, 0, DateTimeKind.Unspecified),
                            Name = "Office Mini Pro",
                            Stock = 12,
                            Warranty = 24,
                            Weight = 4.2000000000000002
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 1, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Creator Max",
                            Stock = 7,
                            Warranty = 12,
                            Weight = 8.9000000000000004
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.PCComponent", b =>
                {
                    b.Property<int>("PCId")
                        .HasColumnType("int");

                    b.Property<string>("ComponentCode")
                        .HasColumnType("char(10)");

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.HasKey("PCId", "ComponentCode");

                    b.HasIndex("ComponentCode");

                    b.ToTable("PCComponents");

                    b.HasData(
                        new
                        {
                            PCId = 1,
                            ComponentCode = "CPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "GPU0000001",
                            Amount = 1
                        },
                        new
                        {
                            PCId = 1,
                            ComponentCode = "RAM0000001",
                            Amount = 2
                        },
                        new
                        {
                            PCId = 3,
                            ComponentCode = "SSD0000001",
                            Amount = 1
                        });
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.Component", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33986.Models.ComponentManufacturer", "ComponentManufacturer")
                        .WithMany("Components")
                        .HasForeignKey("ComponentManufacturerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33986.Models.ComponentType", "ComponentType")
                        .WithMany("Components")
                        .HasForeignKey("ComponentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComponentManufacturer");

                    b.Navigation("ComponentType");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.PCComponent", b =>
                {
                    b.HasOne("PJATK_APBD_Cw7_s33986.Models.Component", "Component")
                        .WithMany("PCComponents")
                        .HasForeignKey("ComponentCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PJATK_APBD_Cw7_s33986.Models.PC", "PC")
                        .WithMany("PCComponents")
                        .HasForeignKey("PCId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Component");

                    b.Navigation("PC");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.Component", b =>
                {
                    b.Navigation("PCComponents");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.ComponentManufacturer", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.ComponentType", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("PJATK_APBD_Cw7_s33986.Models.PC", b =>
                {
                    b.Navigation("PCComponents");
                });
#pragma warning restore 612, 618
        }
    }
}
